kind: Pod
apiVersion: v1
metadata:
  name: myenvconfig
spec: 
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Sai; sleep 5; done"]
    env:
    - name: MYENV
      valueFrom: 
        configMapKeyRef:
          name: mymap
          key: samplefile
