kind: Pod
apiVersion: v1
metadata:
  name: myenvsecret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Sai; sleep 3; done"]
    env:
    - name: MYENVUSER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username.txt
