kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      objtype: deployment
  template:
    metadata:
      name: testpod
      labels:
        objtype: deployment
    spec:
      containers:
      - name: c00
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo Hello-Sai; sleep 5; done"]
        resources:
          requests:
            cpu: "200m"
