apiVersion: v1
kind: Service
metadata:
  name: my-zomato-service
spec:
  type: NodePort
  ports:
  - targetPort: 3000     #this is container port ==> zomato listening port on container
    port: 3000           #this is service objects refernce port

  selector:
    type: food-delivery-app
