kind: Pod
apiVersion: v1
metadata:
  name: myvolsecret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Sai: sleep 5; done"]
    volumeMounts:
    - name: testsecret
      mountPath: "tmp/mysecrets"
  volumes:
  - name: testsecret
    secret:
        secretName: mysecret
